In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5]) #Vector
a


array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
# 2D Array ( Matrix)
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# 3 D ---- # Tensor
np.array ( [[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]] ) 

array([[  2,   3,  33,   4,  45],
       [ 23,  45,  56,  66,   2],
       [357, 523,  32,  24,   2],
       [ 32,  32,  44,  33, 234]])

In [6]:
np.array([20,21,22,23,24,25] , dtype =float)


array([20., 21., 22., 23., 24., 25.])

In [8]:
np.array([1,0,3,0] , dtype =bool)

array([ True, False,  True, False])

In [9]:
np.array([1,2,3] , dtype =complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
np.arange(1,20) #stepsize is 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
np.arange(10) #default start is zero

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1,21,2)# 2 is the strep-size

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
np.arange(1,12).reshape(5,2)

ValueError: cannot reshape array of size 11 into shape (5,2)

In [15]:
np.arange(1,11).reshape(5,3)

ValueError: cannot reshape array of size 10 into shape (5,3)

In [16]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones(3,4) 

TypeError: Cannot interpret '4' as a data type

In [20]:
np.ones((3,4),dtype=int) 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.random.random((4,3)) # range between 0 an 1


array([[0.21577373, 0.82837312, 0.38419711],
       [0.99747992, 0.71582529, 0.29564506],
       [0.20531609, 0.67466247, 0.79445617],
       [0.84032847, 0.66044748, 0.34205227]])

In [28]:
np.random.rand(4,3)

array([[0.72254716, 0.61272988, 0.02931115],
       [0.59364009, 0.14374346, 0.55739863],
       [0.6132302 , 0.60669592, 0.83958334],
       [0.70196026, 0.5139153 , 0.6265888 ]])

In [30]:
np.random.randn(4,3)

array([[ 0.42676062,  2.30515448, -2.09615796],
       [ 1.29706434,  0.00577107, -1.5394992 ],
       [ 1.64815525, -0.03563243, -1.39862137],
       [ 0.95488892,  0.42034087,  3.11390667]])

In [33]:
np.random.randint(1,100)

78

In [39]:
np.random.randint(1,100,100)

array([80, 86, 97, 20, 99, 99, 52, 31, 85, 50, 26, 72, 91, 51, 18, 10,  3,
       98, 44, 76, 35, 66, 59, 20, 47, 62, 79, 69, 40, 86, 19, 77, 65, 19,
       62, 97,  4, 93, 56, 99, 98, 63, 31, 27, 51, 21, 71, 17, 60,  3, 72,
       72,  1, 48, 27, 30, 69,  8, 39, 17, 32, 90, 11, 40, 23, 72, 53, 37,
       60, 26, 23, 33, 13, 45,  7, 96, 35, 17,  7, 91, 81, 48, 44,  1, 35,
       52,  2,  9, 30,  8, 38, 16,  6, 58, 34, 31, 30, 99, 62, 17])

In [41]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a1.shape

(10,)

In [45]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
a2.shape

(3, 4)

In [47]:
a2.astype(float)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [48]:
a3=np.arange(8,dtype=float).reshape(2,2,2)
a3

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [49]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [50]:
a1.size

10

In [51]:
a2.size

12

In [52]:
a3.size

8

In [53]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
float64


In [54]:
a3.astype(int)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
a+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [57]:
a-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [58]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [59]:
a/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [60]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [61]:
a**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [62]:
a %2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [63]:
a//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]], dtype=int32)

In [64]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a>6


array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [66]:
x=np.random.random((3,3))
x

array([[0.98230906, 0.72543376, 0.36688769],
       [0.00406945, 0.54969181, 0.31469486],
       [0.17584975, 0.53645493, 0.4410605 ]])

In [77]:
y=np.round(x*100)
y

array([[98., 73., 37.],
       [ 0., 55., 31.],
       [18., 54., 44.]])

In [78]:
np.max(y)

98.0

In [79]:
np.min(y)

0.0

In [80]:
np.sum(y)

410.0

In [81]:
np.prod(y)

0.0

In [82]:
np.median(y)

44.0

In [83]:
np.mean(y)

45.55555555555556

In [84]:
np.std(y)

27.459510034922776

In [85]:
np.var(y)

754.0246913580247

In [86]:
np.max(y,axis=1)

array([98., 55., 54.])

In [87]:
np.max(y,axis=0)

array([98., 73., 44.])

In [88]:
np.median(y,axis=1)

array([73., 31., 44.])

In [89]:
np.median(y,axis=0)

array([18., 55., 37.])

In [90]:
np.sin(y)

array([[-0.57338187, -0.67677196, -0.64353813],
       [ 0.        , -0.99975517, -0.40403765],
       [-0.75098725, -0.55878905,  0.01770193]])

In [91]:
np.tan(y)

array([[ 6.99853654e-01,  9.19286404e-01, -8.40771255e-01],
       [ 0.00000000e+00, -4.51830879e+01, -4.41695568e-01],
       [-1.13731371e+00,  6.73800101e-01,  1.77046993e-02]])

In [92]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)

In [93]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [95]:
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [96]:
z=np.exp(a1)
z

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [97]:
z1=np.array([1.568,2.7432,8.0213,7.98776])

In [98]:
np.round(z1,decimals=2)


array([1.57, 2.74, 8.02, 7.99])

In [99]:
np.floor(z1)

array([1., 2., 8., 7.])

In [100]:
x1=np.arange(12)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
x1[5]

5

In [103]:
x1[2:6]

array([2, 3, 4, 5])

In [105]:
x1[2:9:3]

array([2, 5, 8])

In [109]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
a[1,::3]

array([4, 7])

In [111]:
a[0:1]

array([[0, 1, 2, 3]])

In [108]:
a[:,2]

array([ 2,  6, 10])

In [112]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [113]:
a[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [114]:
a[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [116]:
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [117]:
for i in x1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [118]:
for i in a:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [119]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [121]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
z1=np.arange(12).reshape(3,4)
z2=np.arange(12,24).reshape(3,4)

In [123]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [125]:
np.hstack((z1,z2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [126]:
np.vstack((z1,z2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [127]:
np.hsplit(a1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [128]:
np.hsplit(a1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [130]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [136]:
np.vsplit(a2,2)

[array([[12, 13, 14],
        [15, 16, 17]]),
 array([[18, 19, 20],
        [21, 22, 23]])]